SET SEARCH_PATH TO "kotlin-spring-data-rest-movies";

TRUNCATE TABLE "actor" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "director" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "character" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "movie" RESTART IDENTITY CASCADE;