spring:
  application:
    name: kotlin-spring-data-rest-movies

  data:
    rest:
      base-path: /api/
      detection-strategy: annotated

  datasource:
    url: jdbc:postgresql://localhost:5432/lab
    username: postgres
    password: postgrespw

  jpa:
    properties:
      hibernate:
        default_schema: ${spring.application.name}

  flyway:
    default-schema: ${spring.application.name}

  jackson:
    property-naming-strategy: SNAKE_CASE

  sql:
    init:
      mode: always
